# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161122_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='titulo',
            field=models.CharField(max_length=1000),
        ),
    ]
